### ISSUE TITLE
question about the transmission pdf

### ISSUE THREAD

**Issue by mclarsen** [knightcrawler25/GLSL-PathTracer#24]
Wouldn't the transmission pdf be weighted by the chance of sampling transmission (i.e., `state.mat.transmission`)?

**Comment by knightcrawler25** [comment]
You're right, it should be weighted by chance of sampling transmission. Thanks for pointing that out. Would not have noticed that since I usually set the transmission to either 0 or 1. 

Also, there seem to be a couple of other issues with transmission and fresnel when comparing the output with Mitsuba. These still have to be fixed.

**Comment by mclarsen** [comment]
No problem. I found your implementation straight forward and its been a good learning resource.

**Comment by knightcrawler25** [comment]
Thank you :) The transmission pdf is fixed in the latest commit after refactoring the BSDF. 
Hopefully the implementation still looks straightforward :P
