### ISSUE TITLE
Image save option does work but with artefacts

### ISSUE THREAD

**Issue by Tetsujinfr** [knightcrawler25/GLSL-PathTracer#40]
Not sure why but when saving a render as an image, there are artefacts, while those do not appear on screen.
I attach an example.

Just me having this issue?
thanks

![glsl_pathtracer_screen_vs_imageExport](https://user-images.githubusercontent.com/29961693/119284665-28955d80-bc38-11eb-8cbe-6746201d5ad0.png)

**Comment by knightcrawler25** [comment]
Seems to be working fine for me on Ubuntu 20.04.

![img_502](https://user-images.githubusercontent.com/11459803/119346092-64233c80-bcb7-11eb-941e-733ee7333641.png)

Not sure why it is showing up like that for you. Maybe try changing the following line to write a .jpg instead and see if that works.

https://github.com/knightcrawler25/GLSL-PathTracer/blob/272915a7e016d87fb0d9675c93c98e7022a54ca8/src/Main.cpp#L124

to:

`stbi_write_jpg(filename.c_str(), w, h, 3, data, w*3);`

**Comment by knightcrawler25** [comment]
The output from the frame buffer is read at the following line and is then passed on to stbi_write_png and I'm not completely sure (since I'm unable to reproduce the issue), but maybe due to the hardware/drivers that you're running on, this read might be behaving weirdly.
https://github.com/knightcrawler25/GLSL-PathTracer/blob/272915a7e016d87fb0d9675c93c98e7022a54ca8/src/core/TiledRenderer.cpp#L411

You might want to try clamping the output from the [tone mapping shader](https://github.com/knightcrawler25/GLSL-PathTracer/blob/master/src/shaders/tonemap.glsl) since, as you mentioned, the artefacts seem to be only in the brightest spots, like the light sources or reflections of the light sources.

**Comment by Tetsujinfr** [comment]
ok so I managed to find a workaround.
You were right, the issue was with `glGetTexImage(GL_TEXTURE_2D, 0, GL_RGB, GL_UNSIGNED_BYTE, *data);` in `TiledRenderer.cpp` , which for some reason messes around with the pixel format data type on my platform (Jetson Xavier NX). If I change the data type from GL_UNSIGNED_BYTE to GL_BYTE, then the artefacts goes away but the overall scene brightness is kind of halved. I have tried many combinations but nothing worked, I am not good enough in Ogl to figure it out.

However, when capturing directly the framebuffer pixels with glReadPixels() then the colors are ok, so did some dirty hacks to insert the saveFrame function at the render stage, in between the scene render and the ImGui render.

I have also swapped STB with OpenCV initially, but I do not think that makes any difference.

closing this issue.

Btw, your project is awsome!
Trying to tweak it to generate higher res images (gonna play with the fov/orientation of the camera and generate tiles and collate them together, unless you have a better idea).
