### ISSUE TITLE
materials pathtrace shader issue

### ISSUE THREAD

**Issue by pbondd** [knightcrawler25/GLSL-PathTracer#41]
Hi,
I have a some suggestions about materials values in pathtrace shader.

I think that gamma correction should be used also if plain color is selected:
https://github.com/knightcrawler25/GLSL-PathTracer/blob/272915a7e016d87fb0d9675c93c98e7022a54ca8/src/shaders/common/pathtrace.glsl#L102-L103
`else`
`    mat.albedo = pow(mat.albedo, vec3(2.2));`

Rigth now, the color selected from picker looks quite different from result. 
The same also applies for metallic-roughness values.
Moreover, roughness value may be 0 if it comes from a texture and this may cause problems with transmission.

https://github.com/knightcrawler25/GLSL-PathTracer/blob/272915a7e016d87fb0d9675c93c98e7022a54ca8/src/shaders/common/pathtrace.glsl#L105-L112

I believe that it is better to apply the 0.001 minimum value also here, like this:

`    if (int(mat.texIDs.y) >= 0) {`
 `       vec2 matRgh;`
`        matRgh = pow(texture(textureMapsArrayTex, vec3(texUV, int(mat.texIDs.y))).zy, vec2(2.2));`
`        mat.metallic = matRgh.x;`
`        mat.roughness = max(matRgh.y, 0.001);`
`    }`
`    else {`
`	mat.metallic = pow(mat.metallic, 2.2);`
`	mat.roughness = max(pow(mat.roughness, 2.2), 0.001);`
`   }`

Last thing, if I'm not mistaken, here should be used the real face normal:
https://github.com/knightcrawler25/GLSL-PathTracer/blob/272915a7e016d87fb0d9675c93c98e7022a54ca8/src/shaders/common/pathtrace.glsl#L122
`Onb(state.normal, T, B);`

Hope this can be helpful.
Thanks for the great work!

**Comment by knightcrawler25** [comment]
Hey!

Your suggestion about gamma correction for the color picker values makes sense and I'll add that fix in. However, I believe metallic, roughness and normal maps are normally in linear space, so, gamma correction isn't required. Even the picker is just a linear value.

Also, I think the gamma correction for metallic roughness maps in the current code `pow(texture(textureMapsArrayTex, vec3(texUV, int(mat.texIDs.y))).zy, vec2(2.2));` isn't right but works as of now because the textures in the repo were manually created and ended up being saved as sRGB.

I'm not very familiar with color spaces so I could be wrong as well. Do let me know if that is the case :)

**Comment by pbondd** [comment]
Hi,

I agree that it should not be necessary to gamma correct metallic roughness. I added it because it was already performed for textures and I found useful to have the same result for the same value.
I'll double check this.

About the last thing I've mentioned, it also involves the following line:
https://github.com/knightcrawler25/GLSL-PathTracer/blob/272915a7e016d87fb0d9675c93c98e7022a54ca8/src/shaders/common/pathtrace.glsl#L122-L124

Does this make sense?

Thanks again!

**Comment by knightcrawler25** [comment]
Oops I missed that in your previous comment. You're right, it should be the geometric normal rather than the front facing normal. It seems to work without issues right now because all shading is done using the front facing normal and so the code treats backfaces the same way as front faces. I'll change it to `state.normal` to avoid confusion

**Comment by pbondd** [comment]
I tried to use a normal map on a material with high transmission value and it fails. With this correction seems to work fine.

**Comment by knightcrawler25** [comment]
Would you be able to post the scene file with the normal map?

**Comment by pbondd** [comment]
Sure, this scene should work:
[GlassNormalMap.zip](https://github.com/knightcrawler25/GLSL-PathTracer/files/6733201/GlassNormalMap.zip)

**Comment by knightcrawler25** [comment]
Thanks for the file. Meanwhile, I've changed the code in a recent commit 9a473379dfc5d3c0c1435d7d46627fffabfa32dc and it seems to have fixed the issue when using your scene file.

**Comment by pbondd** [comment]
Great, thanks!
