### ISSUE TITLE
Sampling the sun

### ISSUE THREAD

**Issue by markusmoenig** [knightcrawler25/GLSL-PathTracer#42]
Is there some example code or a fork which shows how to sample sun light for a given sun light direction ?

Thanks

**Comment by knightcrawler25** [comment]
Hi Markus,

Are you looking to add distant lights to the code? So, basically a light defined just by the direction but not position and area?

**Comment by markusmoenig** [comment]
Hi,

yes exactly. Trying to implement your path tracer in an open world / procedural terrain scenario.

**Comment by knightcrawler25** [comment]
I added support for directional lights. You can try it out using this scene file: [hyperion_distant_light.txt](https://github.com/knightcrawler25/GLSL-PathTracer/files/6732766/hyperion_distant_light.txt)

Direction is inferred from the position. Its the normalized vector defined by light position and origin (0,0,0)

**Comment by markusmoenig** [comment]
Wow, thanks for this. Did not expect you to implement this yourself. Looking at the code the main thing was to set the area to 0 and the distance to infinity for distant lights right ?

As we are not sampling anything we would always get hard shadows I guess. But implementing some sort of disc sampling should not be hard.

Thanks again!

**Comment by knightcrawler25** [comment]
A couple of things had to be changed for directional lights:

1. Light pdf set to 1
2. Area set to 0
3. Light distance set to Infinity
4. MIS was disabled since there is no light sampling involved.

Implementing disc sampling would be similar to the sphere sampling routine: 
It will have some surface area and pdf (maybe without fall off) and MIS can be enabled as the disc will be sampled.

**Comment by markusmoenig** [comment]
Great, thanks for everything, this helps a lot!
