### ISSUE TITLE
Scene list does not work in release mode 

### ISSUE THREAD

**Issue by pcarret** [knightcrawler25/GLSL-PathTracer#50]
Hello,

The scene list looks ok in Debug mode but is filled only by first .scene file in Release Configuration

Thanks for this amazing work
Philippe

**Comment by knightcrawler25** [comment]
I'm unable to reproduce this. Will you be able to try compiling with a different platform toolset?

![image](https://user-images.githubusercontent.com/11459803/136635729-952926fa-e1f7-4b94-8710-5c9285332b6f.png)

**Comment by er888kh** [comment]
> Hello,
> 
> The scene list looks ok in Debug mode but is filled only by first .scene file in Release Configuration
> 
> Thanks for this amazing work Philippe

Couldn't reproduce this with cmake on linux (GCC 11.1)
Can you provide a screenshot or add a few lines around [here](https://github.com/knightcrawler25/GLSL-PathTracer/blob/53947921eb7748eda20dc031cc296814cc8f8262/src/Main.cpp#L289) to print `scenes.data()`?

**Comment by pcarret** [comment]
You are right i*t works with vc141* Release mode and it fails with vc142
Release mode   .
So it's maybe a bug in UI library itself

**Comment by knightcrawler25** [comment]
I'm not really familiar with imgui code but it looks like some sort of compiler + imgui incompatibility. Since it happens only in Release mode, could you also try disabling optimization while on v142 toolset and see if that makes any difference? Also what version of VS are you on? 16.11.4?

![image](https://user-images.githubusercontent.com/11459803/136651487-465d05b5-d07b-4c29-a22f-2578abeec9d6.png)
