### ISSUE TITLE
Lack of test files

### ISSUE THREAD

**Issue by tigrazone** [knightcrawler25/GLSL-PathTracer#66]
Please when you implement new features, add test files for checking it

**Comment by knightcrawler25** [comment]
All the scene files should be available at the link mentioned in the readme (https://drive.google.com/file/d/1UFMMoVb5uB7WIvCeHOfQ2dCQSxNMXluB/view). 

Its split between .scene files and gltf files that utilise the most recent feature addtions like alpha testing etc.

**Comment by tigrazone** [comment]
Thank you for update.
marble_bust_01.bin is not used by scene files? I cant find references to it

**Comment by knightcrawler25** [comment]
I probably removed the gltf file and forgot to delete the .bin. 

You can get the gltf here: https://polyhaven.com/a/marble_bust_01

**Comment by tigrazone** [comment]
Thank you!

**Comment by tigrazone** [comment]
I remember also
test_volume_cube.scene and test_volume_cube_sss.scene
Why this files render on another way? You changed volume format or processing?
Please add this files also

**Comment by tigrazone** [comment]
I see you remove extinction processing. This parameter was good for materials ;-)

**Comment by knightcrawler25** [comment]
> test_volume_cube.scene and test_volume_cube_sss.scene

These files only work with the code in the volumes branch. The dev branch has a simplified volume system similar to how MagicaVoxel handles volumes. I'll add some sample files when I'm done adding direct lighting for volumes.

> I see you remove extinction processing. This parameter was good for materials ;-)

Extinction and atDistance were used for volumetric absorption earlier. It's handled differently now:
- mediumType should be set to absorb
- mediumColor can be used instead of Extinction 
- mediumDensity can be used instead of AtDistance

These changes allow extinction to work the same way as before but with some additional medium types:

Absorption:
![absorption](https://user-images.githubusercontent.com/11459803/149539494-6b5d2f1b-8249-4fa8-8f5b-7e5f6a0729eb.png)

Scattering:
![scattering](https://user-images.githubusercontent.com/11459803/149539499-a3bb322f-87e1-4ba9-9186-cc7c470a155d.png)

Emission:
![Emissive](https://user-images.githubusercontent.com/11459803/149540237-178d92af-0eea-410e-bf62-b7a488a87b33.png)

**Comment by tigrazone** [comment]
Maybe unite these parameters like smallupbp and corona render do?
for example, smallupbp input file with volumes:
https://github.com/PetrVevoda/smallupbp/blob/master/scenes/stilllife/stilllife.obj.aux

**Comment by knightcrawler25** [comment]
That's actually what the code in the volumes branch does with sigma_a and sigma_s but those parameters are non intuitive and it also requires a bunch of extra code for checks etc. I wanted a simpler method mainly so that it's easy to add subsurface scattering later by inverting the diffuse lobe and just setting the subsurface color using the medium color parameter.
