### ISSUE TITLE
(Question) Why was transmission extinction removed from the BRDF ?

### ISSUE THREAD

**Issue by Nolram12345** [knightcrawler25/GLSL-PathTracer#68]
Older versions before the BRDF rework had an option for extinction of spec. transmission. Why exactly was this option removed ? Was it incompatible with the new BRDF model that allows for volumes ?

**Comment by knightcrawler25** [comment]
Since I added support for volumes, the Extinction and atDistance parameters weren't needed as they were used to model volumetric absorption. Technically, they were volume properties rather than surface properties.

I've mentioned this change in another issue:

https://github.com/knightcrawler25/GLSL-PathTracer/issues/66#issuecomment-1013221790

**Comment by Nolram12345** [comment]
Ah, this explains the change. However, extinction was actually a really interesting property for spec. transmission, as it allowed for modelling other types of "glass" volumes.
Here is an example from my fork of the renderer based on the old model :
![render_443](https://user-images.githubusercontent.com/37701550/154308414-b06e461c-0105-4a44-b007-65578a1a415e.png)
As you can see, the intensity of the extinction tint gets stronger with higher object depth/thickness, an effect that can be observed in real glass. As far as I know this is not possible to model anymore with the current BRDF ?

**Comment by Nolram12345** [comment]
Oh wait, I only now read the comment you made in the other thread - thanks for clearing that up, that explains it.
Thank you for your work !
