### ISSUE TITLE
Crash when trying to open bedroom scene 

### ISSUE THREAD

**Issue by ychding11** [knightcrawler25/GLSL-PathTracer#7]
PathTracer_d.exe!GLSLPathTracer::RenderOptions::operator=(const GLSLPathTracer::RenderOptions & __that)	C++
	PathTracer_d.exe!loadScene(int index) Line 55	C++
 	PathTracer_d.exe!main() Line 230	C++
 	[External Code]	

On Windows 10, Debug version.
I think you should put assignment statement after checking.
```

        scene = LoadScene(std::string("./assets/")+sceneFilenames[index]);
        scene->renderOptions = renderOptions;
	if (!scene)
	{
		std::cout << "Unable to load scene\n";
		exit(0);
	}
```

**Comment by knightcrawler25** [comment]
Hi,

Thanks for letting me know. I'm currently refactoring the entire code so that its easier to use. Also, due to performance issues I want to try moving the code to use compute shaders and see how it goes. I will be fixing this issue along with the other issues when i'm done with updating the codebase :)

**Comment by knightcrawler25** [comment]
Closing since this is fixed now
